#!/bin/bash
#
. ~/.bashrc
cd _posh
#
RES="../src/main/res"
CP=`ls -m *jar`
echo "- `pwd`"
#
_CLEAR=("icons/*"
 "experiences.json" "$RES/raw/markets.json"
 "$RES/mipmap-*/market_*.png" "$RES/mipmap-*/department_*.png"
)
#
function clear() {
 echo "- clear"
 for i in "${_CLEAR[@]}"; do echo "  ... $i"; rm $i; done
 echo "finished - clear"
}
function build() {
 echo "- build"
 echo "  ... executing app.kts"
 kotlinc -cp ${CP//[ ,]?/:} -script app.kts \
    && echo "finished - build"
}
function rebuild() {
  clear
  build
}
#
if [ ! $1 ]; then
  build
  exit $?
fi
#
case $1 in
    clear | build | rebuild )
        eval $1;
        exit $?
    ;;
    * ) echo "usage: #$0 clear | build* | rebuild"
        exit 1
esac
